import { PageLayout } from "@/components/layout/PageLayout";
import { Card, Cta, Hero, List, SEO, Section, Tags, icons } from "./platform-content";
import { Link } from "react-router-dom";

export default function Home() {
  return <PageLayout><SEO title="Caribbean Alternative Finance | Invoice & Receivables Funding for SMEs" description="Unlock working capital from invoices, contracts, receivables, and recurring revenue through a regional Caribbean alternative finance platform." />
    <Hero eyebrow="Caribbean invoice exchange · receivables marketplace · revenue-based finance" title="Turn unpaid invoices into working capital." description="A regional finance platform helping Caribbean businesses unlock capital from contracts, receivables, invoices, and recurring revenue.">
      <div className="space-y-4"><div className="flex flex-wrap gap-3">{["Built for Caribbean SMEs","Invoices, contracts, and recurring revenue","Designed for regulated capital partners"].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-slate-100">{x}</span>)}</div><div className="pt-4"><Card title="Hotel Supplier Invoice"><p>Asset type: Invoice</p><p>Buyer type: Hotel group</p><p>Term: 60 days</p><p>Status: Under review</p><p>Risk grade: Pending</p><p>Verification: Documents submitted</p></Card></div></div>
    </Hero>
    <Section title="Caribbean businesses do the work. Then wait months to get paid."><List items={["Government and corporate payment cycles can create cash flow pressure.","Many SMEs lack the collateral required for traditional bank loans.","Tourism and service businesses often have predictable revenue but limited working capital.","Strong businesses can still struggle when cash arrives too late."]} /></Section>
    <Section title="Finance based on future cash flow, not just collateral." description="Three connected rails for turning verified obligations and predictable revenue into reviewed funding opportunities."><div className="grid gap-6 md:grid-cols-3"><Card title="Invoice Exchange" icon={<icons.FileCheck2/>}>SMEs submit verified invoices from approved buyers and request early payment from capital providers.</Card><Card title="Receivables Marketplace" icon={<icons.Landmark/>}>Contracts, purchase orders, and receivables can be reviewed, structured, and presented as funding opportunities.</Card><Card title="Revenue-Based Financing" icon={<icons.LineChart/>}>Businesses with recurring or predictable revenue can access capital and repay through a share of future receipts.</Card></div></Section>
    <Section title="Built for the three sides of Caribbean SME finance." dark><div className="grid gap-6 md:grid-cols-3">{[["For SMEs","Request funding using invoices, contracts, receivables, bookings, or recurring revenue.","Apply for Funding","/for-smes"],["For Investors","Review verified Caribbean receivables and participate in structured SME financing opportunities.","Join Investor List","/for-investors"],["For Institutions","Explore supplier finance pilots, guarantee structures, SME programs, and regional market development partnerships.","Partner With Us","/for-institutions"]].map(([t,c,cta,href])=><div key={t} className="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 className="text-2xl font-semibold text-white">{t}</h3><p className="mt-3 text-slate-300">{c}</p><Link className="mt-6 inline-flex items-center gap-2 font-semibold text-amber-300" to={href}>{cta}<icons.ArrowRight className="h-4 w-4"/></Link></div>)}</div></Section>
    <Section title="Built for finance, not hype."><Tags items={["Business verification","Contract and invoice review","Debtor risk scoring","KYC / KYB onboarding","Investor suitability controls","Audit-friendly reporting","Regulatory-first structure"]}/></Section>
    <Section title="A regional financing gap hiding in plain sight." description="Across the Caribbean, SMEs often have confirmed work but limited working capital. Caribbean Alternative Finance is designed to help convert verified receivables into fundable assets."><div /></Section>
    <Cta title="Help build the Caribbean’s alternative capital market." />
  </PageLayout>;
}
